### ISSUE TITLE
HTTPS on ctwatch.net

### ISSUE THREAD

**Issue by rugk** [certificate-transparency-watch/ct-watch-www#13]
Why don't you redirect to HTTPS at ctwatch.net and why don't you provide HTTPS at api.ctwatch.net at all?

And why do you use a bad Cloudflare SSL certificate for ctwatch.net?

**Comment by tomfitzhenry** [comment]
Thanks for the bug report.

There's no great reason I don't redirect HTTP to HTTPS on ctwatch.net . I just haven't got round to prioritising it. I suppose I'd prefer not to break HTTP clients that don't follow redirects (e.g. curl without -L), but mostly I just hadn't considered it much.

api.ctwatch.net is available via HTTPS! https://api.ctwatch.net/domain/ietf.org

What is bad about the certificate used for ctwatch.net?

**Comment by rugk** [comment]
> api.ctwatch.net is available via HTTPS! https://api.ctwatch.net/domain/ietf.org

Ah yes, you're right. Firefox just showed no lock and hid the `https://` for the RSS feed.

> What is bad about the certificate used for ctwatch.net?

As I see you use the free TLS cert by Cloudflare. Well... that's essentially a cert with MITM-built-in as Cloudflare intercepts every connection. So that's no end-to-end-security.
More info:
* https://serverfault.com/questions/505451/how-secure-is-cloudflares-basic-ssl
* https://info.ssl.com/the-real-cost-of-a-cloudflare-free-ssl-certificate/
* https://scotthelme.co.uk/cloudflares-great-new-features-and-why-i-wont-use-them/

**Comment by tomfitzhenry** [comment]
> Well... that's essentially a cert with MITM-built-in as Cloudflare intercepts every connection. So that's no end-to-end-security.

Ah yes, I agree. By using CloudFlare, ctwatch.net still benefits from the user <-> ISP link being secured, which I'd bet is the weakest chain. Ultimately however, ctwatch.net loses end-to-end security.

However, I have to balance that with what CloudFlares offers for minimal effort:
* HTTP caching
* DDOS protection
* trivial SSL setup

Perhaps I could set that all up (squid, SSL on nginx) and maintain it, but then I'd have less time to work on features, and given how much time I dedicate to this, it's more beneficial for me to work on features at this moment.

**Comment by rugk** [comment]
BTW I've [reported the issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1206905) with the missing padlock on an RSS site.

**Comment by tomfitzhenry** [comment]
:+1:

**Comment by rugk** [comment]
You could still use cloudflare - just with an own certificate. So you would still have some caching mechanisms and DDOS protection.
And about the setup you maybe want to consider [Let's Encrypt](https://letsencrypt.org/) where everything is automated, free and it's really simple to set up.

**Comment by tomfitzhenry** [comment]
But if I continue to use Cloudflare, albeit with my own certificate, I'm still vulnerable to MITM.

I'll consider Let's Encrypt when it's ready.

Closing for now.
